# These values are available to all subcharts BUT vie Values.global
# Values.appSelector - DOESNT WORK
# Values.global.appSelector - OK
global:
  appSelector:
    app: "gomaster-{{ .Release.Name }}"

# Used to parameter "gomaster-service" subchart
# These values override those in subchart values.yaml
gomaster-service:
  httpPort: 80

# Used to parameter "gomaster-deployment" subchart
# These values override those in subchart values.yaml
gomaster-deployment:
  imageName: "docker.io/alanmpinder/gomaster:latest"
